# Generated by Django 4.0.2 on 2022-02-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bids_bid_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='BidList',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentList',
        ),
    ]
