# Generated by Django 4.0.2 on 2022-02-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_date_created_bidlist_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='auctioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
