# Generated by Django 4.0.2 on 2022-02-19 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlist_winner_alter_auctionlist_auctioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
