# Generated by Django 4.0.2 on 2022-02-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bidlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlist',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist'),
        ),
    ]
