# Generated by Django 4.0.2 on 2022-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlist_startingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
